# -*- coding: utf-8 -*-
"""image_generation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xJZuVpDJShtwmJzsTL-Iri2gYln9xqZ
"""

!pip install diffusers transformers accelerate torch safetensors

from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompt = "A futuristic AI laboratory with robots learning machine learning, ultra realistic, 4K"

image = pipe(prompt).images[0]

image.save("generated_image.png")

image